const EMAIL_TEMPLATE_KEYS = {
  CAMP_REMINDER_24H: 'CAMP_REMINDER_24H',
  CAMP_REMINDER_7D: 'CAMP_REMINDER_7D',
  MEMBER_REMINDER_24H: 'MEMBER_REMINDER_24H',
  MEMBER_REMINDER_7D: 'MEMBER_REMINDER_7D'
};

module.exports = {
  EMAIL_TEMPLATE_KEYS
};
