const EMAIL_TEMPLATE_KEYS = {
  NEW_APPLICATION_NOTIFICATION: 'NEW_APPLICATION_NOTIFICATION',
  APPLICATION_APPROVED: 'APPLICATION_APPROVED',
  APPLICATION_REJECTED: 'APPLICATION_REJECTED',
  CAMP_REMINDER_24H: 'CAMP_REMINDER_24H',
  CAMP_REMINDER_7D: 'CAMP_REMINDER_7D',
  MEMBER_REMINDER_24H: 'MEMBER_REMINDER_24H',
  MEMBER_REMINDER_7D: 'MEMBER_REMINDER_7D',
  SHIFT_BULK_INVITE_ALL: 'SHIFT_BULK_INVITE_ALL',
  SHIFT_DIRECT_ASSIGNMENT: 'SHIFT_DIRECT_ASSIGNMENT',
  SURVEY_ASSIGNMENT: 'SURVEY_ASSIGNMENT'
};

module.exports = {
  EMAIL_TEMPLATE_KEYS
};
