const NOTIFICATION_TYPES = Object.freeze({
  APPLICATION_SUBMITTED: 'APPLICATION_SUBMITTED',
  APPLICATION_STATUS_UPDATED: 'APPLICATION_STATUS_UPDATED',
  SHIFT_CREATED: 'SHIFT_CREATED',
  SHIFT_UPDATED: 'SHIFT_UPDATED',
  SHIFT_DELETED: 'SHIFT_DELETED',
  SHIFT_SIGNUP: 'SHIFT_SIGNUP',
  SHIFT_UNSIGNUP: 'SHIFT_UNSIGNUP',
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_UPDATED: 'TASK_UPDATED',
  TASK_COMMENTED: 'TASK_COMMENTED'
});

module.exports = {
  NOTIFICATION_TYPES
};
